name: Scala CI

on:
  push:
    branches: [ main ]
    paths:
      - 'data-engineering/tp-data-processing-framework/src/**'
  pull_request:
    branches: [ main ]

jobs:
  run-my-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
      working-directory: data-engineering/tp-data-processing-framework
