name: Test data-processing-framework

on:
  push:
    branches: [ "main" ]
    paths:
      - 'data-engineering/tp-data-processing-framework/src/**'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
 run:
  working-directory: ./data-engineering/tp-data-processing-framework

jobs:
  run-my-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Coursier dependencies
      uses: coursier/cache-action@v6

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install sbt
      run: |
        curl -L -o sbt.zip https://github.com/sbt/sbt/releases/download/v1.10.7/sbt-1.10.7.zip
        unzip sbt.zip -d $HOME/sbt
        echo "$HOME/sbt/sbt/bin" >> $GITHUB_PATH
        
    - name: Run tests
      run: sbt test
