name: tp-data-processing-framework CI

on:
  push:
    branches: [ main ]

defaults:
 run:
  working-directory: ./data-engineering/tp-data-processing-framework

jobs:
  run-my-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Coursier dependencies
      uses: coursier/cache-action@v6
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
        restore-keys: |
          ${{ runner.os }}-coursier-

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install sbt
      run: |
        curl -L -o sbt.zip https://github.com/sbt/sbt/releases/download/v1.10.7/sbt-1.10.7.zip
        unzip sbt.zip -d /usr/local
        mv /usr/local/sbt-1.10.7/usr/local/sbt
        echo "::add-path::/usr/local/sbt/bin"
        
    - name: Run tests
      run: sbt test
